rewards:
  - id: squire_rank
    name: "&7Squire"
    material: IRON_SWORD
    slot: 10
    lore:
      - "&7The journey begins."
      - "&7You are but a humble squire."
      - ""
      - "&7Learn the ways of the realm."
      - "&7Earn your place among the knights."
    requiredPlaytime: 1800 # 30 minutes
    commands:
      - "give %player% iron_sword 1"
      - "give %player% bread 10"
      - "give %player% iron_ingot 5"
      - "say %player% has become a Squire!"
      - 'title %player% title {"text":"Squire","color":"gray","bold":true}'
      - 'title %player% subtitle {"text":"The story begins...","color":"dark_gray","italic":true}'

  - id: knight_rank
    name: "&fKnight"
    material: IRON_CHESTPLATE
    slot: 12
    lore:
      - "&fA sworn protector of the land."
      - "&fYour valor has been proven."
      - ""
      - "&fDefend the weak."
      - "&fFight with honor."
    requiredPlaytime: 7200 # 2 hours
    commands:
      - "give %player% iron_chestplate 1"
      - "give %player% shield 1"
      - "give %player% iron_ingot 10"
      - "give %player% cooked_beef 10"
      - "say %player% is now a brave Knight!"
      - 'title %player% title {"text":"Knight","color":"white","bold":true}'
      - 'title %player% subtitle {"text":"Honor and steel guide your path.","color":"gray","italic":true}'

  - id: paladin_rank
    name: "&ePaladin"
    material: GOLDEN_SWORD
    slot: 14
    lore:
      - "&eA champion of light."
      - "&eYour deeds inspire the realm."
      - ""
      - "&eLet your faith be your shield."
      - "&eBring justice with every strike."
    requiredPlaytime: 21600 # 6 hours
    commands:
      - "give %player% golden_sword 1"
      - "give %player% golden_apple 3"
      - "give %player% gold_ingot 12"
      - "give %player% emerald 5"
      - "say %player% has earned the title of Paladin!"
      - 'title %player% title {"text":"Paladin","color":"yellow","bold":true}'
      - 'title %player% subtitle {"text":"Faith is your weapon. Light is your shield.","color":"gold","italic":true}'


  - id: warlock_rank
    name: "&5Warlock"
    material: ENCHANTED_BOOK
    slot: 16
    lore:
      - "&5Master of arcane secrets."
      - "&5You delve into forbidden magic."
      - ""
      - "&5Wield your power wisely."
      - "&5Knowledge is your true weapon."
    requiredPlaytime: 43200 # 12 hours
    commands:
      - "give %player% ender_pearl 5"
      - "give %player% experience_bottle 10"
      - "give %player% blaze_powder 6"
      - "give %player% redstone 16"
      - "say %player% has unlocked the dark arts as a Warlock!"
      - 'title %player% title {"text":"Warlock","color":"dark_purple","bold":true}'
      - 'title %player% subtitle {"text":"The arcane whispers your name.","color":"light_purple","italic":true}'


  - id: dragonlord_rank
    name: "&cDragonlord"
    material: DRAGON_HEAD
    slot: 22
    lore:
      - "&cRuler of flame and sky."
      - "&cYour legend echoes through time."
      - ""
      - "&cFew dare challenge your might."
      - "&cCommand dragons and destiny alike."
    requiredPlaytime: 86400 # 24 hours
    commands:
      - "give %player% dragon_head 1"
      - "give %player% fire_charge 10"
      - "give %player% diamond 5"
      - "give %player% netherite_ingot 10"
      - "say %player% has become the mighty Dragonlord!"
      - 'title %player% title {"text":"Dragonlord","color":"red","bold":true}'
      - 'title %player% subtitle {"text":"Rule the skies. Command your legend.","color":"dark_red","italic":true}'
