name: PlayTimePulse
version: '${project.version}'
main: com.github.souldevhub.playTimePlugin.PlaytimePulse
api-version: '1.21'
author: souldevhub
description: Track player playtime and reward them for playing
website: https://github.com/Souldevhub/PlayTimePulse
softdepend: [PlaceholderAPI]

commands:
  playtime:
    description: Checks your playtime and open the rewards GUI
    usage: /playtime
    aliases: [pt]