name: PlayTimePulse
version: '1.0.2'
main: com.github.souldevhub.playTimePlugin.PlayTimePlugin
api-version: '1.21'
authors: [ github.com/souldevhub ]
description: Playtime tracker + ranks for engagement.
website: instagram.com/shiawase.re
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE #
      required: false
commands:
  playtime:
    description: Main command for playtime tracking and management.
    usage: |-
      §c/playtime - Shows your playtime and GUI
      §c/playtime add <player> <hours>h [<minutes>m] - Add playtime to a player
      §c/playtime reset <player> - Reset player's playtime and claimed rewards
    aliases: [pt, playrank]
    permission: playtime.use

permissions:
  playtime.use:
    default: true
    description: Level 1 permission to use playtime commands
  playtime.admin:
    default: op
    description: Level 2 permission for admin commands
    children:
      playtime.use: true
