name: PlayTimeTracker
version: '1.0.1'
main: com.github.souldevhub.playTimePlugin.PlayTimePlugin
api-version: '1.21'
authors: [ github.com/souldevhub ]
description: Playtime tracker + ranks for engagement.
website: instagram.com/shiawase.re
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE #
      required: false
commands:
  playtime:
    description: Shows your playtime
    usage: /playtime
    aliases: [pt, playrank]
